build:
	pebble build

install:
	pebble install --phone 172.27.221.14

clean:
	pebble clean

list:
	pebble list --phone 172.27.221.14

logs:
	pebble logs --phone 172.27.221.14

screen:
	pebble screenshot --phone 172.27.221.14

